### ISSUE TITLE
Got 503 error with cn site

### ISSUE THREAD

**Issue by jiangshanmeta** [cascandaliato/leetcode-badge#27]
this is my cn leetcode profile: https://leetcode.cn/u/jiangshanmeta/

recently I got this 503 error.
![截图 2024-01-09 23-27-08](https://github.com/cascandaliato/leetcode-badge/assets/13798212/3b3e1ace-3b36-4ee2-a0ce-87ab9144a8c8)

that worked fine about two weeks ago.

help to check

**Comment by cascandaliato** [comment]
Some API endpoints for LeetCode China have changed. I get error 503 when I run the same query used by the code:
```bash
$ curl -X POST -H "Content-Type: application/json" -d '{"variables": { "userSlug" : "jiangshanmeta" }, "query": "query userProfilePublicProfile($userSlug: String!) { userProfilePublicProfile(userSlug: $userSlug) { siteRanking profile { userSlug realName userAvatar} }}" }' https://leetcode-cn.com/graphql
<html>
<head><title>503 Service Temporarily Unavailable</title></head>
<body>
<center><h1>503 Service Temporarily Unavailable</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

I'll need some time to identify the new endpoints.

**Comment by cascandaliato** [comment]
I just had to change `https://leetcode-cn.com` to `https://leetcode.cn`.

I'm having issues with Vercel deploying the latest changes. I'll let you know when the fix has been deployed.

**Comment by cascandaliato** [comment]
Fixed.

The badge in your GitHub homepage needs to be replaced with

`[![LeetCode user jiangshanmeta](https://img.shields.io/badge/dynamic/json?style=flat-square&labelColor=black&color=%23ffa116&label=Solved&query=solvedOverTotal&url=https%3A%2F%2Fleetcode-badge.vercel.app%2Fapi%2Fusers%2Fjiangshanmeta%2Fcn%2F&logo=leetcode&logoColor=yellow)](https://leetcode.cn/jiangshanmeta/)`

[![LeetCode user jiangshanmeta](https://img.shields.io/badge/dynamic/json?style=flat-square&labelColor=black&color=%23ffa116&label=Solved&query=solvedOverTotal&url=https%3A%2F%2Fleetcode-badge.vercel.app%2Fapi%2Fusers%2Fjiangshanmeta%2Fcn%2F&logo=leetcode&logoColor=yellow)](https://leetcode.cn/jiangshanmeta/)
